{% set version = "4.1" %}

package:
  name: django-extensions
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/django-extensions/django_extensions-{{ version }}.tar.gz
  sha256: 7b70a4d28e9b840f44694e3f7feb54f55d495f8b3fa6c5c0e5e12bcb2aa3cdeb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - django >=4.2
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - django_extensions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: Extensions for Django.

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
