{% set version = "3.2.3" %}

package:
  name: django-extensions
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/django-extensions/django-extensions-{{ version }}.tar.gz
  sha256: 44d27919d04e23b3f40231c4ab7af4e61ce832ef46d610cc650d53e68328410a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2

test:
  imports:
    - django_extensions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/django-extensions/django-extensions
  license: MIT
  license_file: LICENSE
  summary: Extensions for Django.

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
